name: jito_matrimony
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rflutter_alert: ^1.0.3
  full_screen_image: ^1.0.2
  image_picker: ^0.8.0+1
  image_cropper: ^1.4.0
  path_provider: ^2.0.2
  fluttertoast: ^8.0.7
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  pinput: ^0.2.6
  splashscreen: ^1.3.5
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6
  pausable_timer: ^0.2.0+1
  photo_view: ^0.11.1
  url_launcher: ^6.0.3
  multiselect_formfield: ^0.1.6
  searchable_dropdown: ^1.1.3
  multi_select_flutter: ^4.0.0
  firebase_messaging: ^10.0.0
  shared_preferences: ^2.0.5
  progress_indicators: ^1.0.0
  progress_dialog: ^1.2.4
  chopper: ^4.0.0
  provider: ^4.0.5
  json_annotation: ^4.0.1
  logging: ^1.0.1
  connectivity: ^3.0.3
  flutter_local_notifications: ^5.0.0+1
  overlay_support: ^1.0.0
  flutter_screenutil: ^4.0.2+3
  carousel_slider: ^2.3.1
  flutter_inappwebview: ^5.3.2
  intent: ^1.4.0
  custom_progress_dialog: ^1.0.5
  flutter_tags: ^0.1.9
  device_info: ^2.0.2
  android_multiple_identifier: ^1.0.3
  loadmore: ^2.0.1
  lazy_load_scrollview: ^1.3.0
  pdf: ^3.4.2
  video_player: ^1.0.1
  chewie: ^0.12.2
  flutter_xlider: ^3.4.0
  hexcolor: ^2.0.3
  printing: ^5.4.3
  flutter_open_whatsapp: ^0.1.2
  flutter_share: ^2.0.0
  image_gallery_saver: ^1.6.9
  share: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5
  chopper_generator: ^4.0.0
  unique_identifier: ^0.0.3
  json_serializable: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - Assets/
    - Assets/my_favourites_fin.jpg
    - Assets/login_bg.jpg
    - Assets/logo.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
